//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool runOnStartup {
            get {
                return ((bool)(this["runOnStartup"]));
            }
            set {
                this["runOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinToTrayWhenOpening {
            get {
                return ((bool)(this["MinToTrayWhenOpening"]));
            }
            set {
                this["MinToTrayWhenOpening"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinToTrayWhenClosing {
            get {
                return ((bool)(this["MinToTrayWhenClosing"]));
            }
            set {
                this["MinToTrayWhenClosing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainTimerReminderEnabled {
            get {
                return ((bool)(this["MainTimerReminderEnabled"]));
            }
            set {
                this["MainTimerReminderEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal MainTimerReminderTimeInSeconds {
            get {
                return ((decimal)(this["MainTimerReminderTimeInSeconds"]));
            }
            set {
                this["MainTimerReminderTimeInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PcIdleReminderEnabled {
            get {
                return ((bool)(this["PcIdleReminderEnabled"]));
            }
            set {
                this["PcIdleReminderEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PcIdleReminderAction {
            get {
                return ((int)(this["PcIdleReminderAction"]));
            }
            set {
                this["PcIdleReminderAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PcIdleReminderTimeInSeconds {
            get {
                return ((decimal)(this["PcIdleReminderTimeInSeconds"]));
            }
            set {
                this["PcIdleReminderTimeInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainTimerReminderDisabledAfterGoinOn {
            get {
                return ((bool)(this["MainTimerReminderDisabledAfterGoinOn"]));
            }
            set {
                this["MainTimerReminderDisabledAfterGoinOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableIdleWhenTimerRunning {
            get {
                return ((bool)(this["DisableIdleWhenTimerRunning"]));
            }
            set {
                this["DisableIdleWhenTimerRunning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Show1MnWarning {
            get {
                return ((bool)(this["Show1MnWarning"]));
            }
            set {
                this["Show1MnWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ModeDev {
            get {
                return ((bool)(this["ModeDev"]));
            }
            set {
                this["ModeDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReminderTimerInStatusBar {
            get {
                return ((bool)(this["ReminderTimerInStatusBar"]));
            }
            set {
                this["ReminderTimerInStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IdleTimerStatusInStatusBar {
            get {
                return ((bool)(this["IdleTimerStatusInStatusBar"]));
            }
            set {
                this["IdleTimerStatusInStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ModeTestForLockPc {
            get {
                return ((bool)(this["ModeTestForLockPc"]));
            }
            set {
                this["ModeTestForLockPc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ModeTestForClosePC {
            get {
                return ((bool)(this["ModeTestForClosePC"]));
            }
            set {
                this["ModeTestForClosePC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isClosing {
            get {
                return ((bool)(this["isClosing"]));
            }
            set {
                this["isClosing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Theme {
            get {
                return ((int)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color DarkThemeColor {
            get {
                return ((global::System.Drawing.Color)(this["DarkThemeColor"]));
            }
            set {
                this["DarkThemeColor"] = value;
            }
        }
    }
}
